name: Deploy prod

on:

  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag to deploy"
        required: true

env:
  REGISTRY: ghcr.io

jobs:
  deploy-prod:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: read

    steps:

      - name: lowercase repo name
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: log in to the Container REGISTRY
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify tag image exists
        run: |
          docker manifest inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend:${{ github.event.inputs.tag }} > /dev/null
          docker manifest inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend:${{ github.event.inputs.tag }} > /dev/null

      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Change backend and frontend name image in the compose file
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.CI_USER }}@${{ secrets.CI_TAILSCALE_HOST }} << 'EOF'
          sudo sed -i "s|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend.*|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend:${{ github.event.inputs.tag }}|" /opt/d4g/docker-compose.yml
          sudo sed -i "s|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend.*|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend:${{ github.event.inputs.tag }}|" /opt/d4g/docker-compose.yml
          EOF

      - name: Clean up & Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.CI_USER }}@${{ secrets.CI_TAILSCALE_HOST }} << 'EOF'
            sudo docker compose -f /opt/d4g/docker-compose.yml pull
            sudo docker compose -f /opt/d4g/docker-compose.yml up -d --remove-orphans
            sudo docker image prune -f
          EOF
